name: destroy-infra

on:
  push:
    branches:
      - develop
  workflow_dispatch:   # 👈 SOLO MANUAL

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🔥 PURGE APIM (SI EXISTE)
      - name: Purge APIM soft-deleted
        run: |
          az apim deletedservice purge \
            --service-name apim-cardops-demo \
            --location eastus || echo "No APIM to purge"

      # 💣 BORRAR TODO EL RESOURCE GROUP
      - name: Destroy Resource Group
        run: |
          az group delete \
            --name rg-cardops-demo \
            --yes \
            --no-wait
