name: destroy-infra

on:
  workflow_dispatch:   # 👈 SOLO MANUAL

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy infrastructure
        run: pwsh ./destroy.ps1
